create extension if not exists pgcrypto;
create extension if not exists citext;
create type user_role as enum ('platform_admin','venue_admin');
create type campaign_status as enum ('draft','scheduled','active','paused','complete');
create type prize_status as enum ('disabled','active','exhausted');

create table venues (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, timezone text not null default 'America/Los_Angeles', active boolean not null default true, prizes_enabled boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table users (id uuid primary key default gen_random_uuid(), venue_id uuid references venues(id) on delete cascade, email citext not null unique, password_hash text not null, role user_role not null default 'venue_admin', active boolean not null default true, created_at timestamptz not null default now());
create table venue_games (venue_id uuid not null references venues(id) on delete cascade, game_id text not null, enabled boolean not null default true, rotation_position integer not null default 0, config jsonb not null default '{}', updated_at timestamptz not null default now(), primary key(venue_id,game_id));
create table player_sessions (id uuid primary key default gen_random_uuid(), venue_id uuid not null references venues(id) on delete cascade, username varchar(24) not null, browser_token uuid not null default gen_random_uuid(), last_seen_at timestamptz not null default now(), created_at timestamptz not null default now());
create table game_sessions (id uuid primary key default gen_random_uuid(), venue_id uuid not null references venues(id) on delete cascade, game_id text not null, state jsonb not null default '{}', starts_at timestamptz, ends_at timestamptz, created_at timestamptz not null default now());
create table game_entries (id uuid primary key default gen_random_uuid(), game_session_id uuid not null references game_sessions(id) on delete cascade, player_session_id uuid not null references player_sessions(id) on delete cascade, score numeric, payload jsonb not null default '{}', created_at timestamptz not null default now(), unique(game_session_id,player_session_id));
create table campaigns (id uuid primary key default gen_random_uuid(), venue_id uuid references venues(id) on delete cascade, name text not null, status campaign_status not null default 'draft', starts_at timestamptz, ends_at timestamptz, weight integer not null default 1 check(weight>0), created_at timestamptz not null default now());
create table campaign_creatives (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references campaigns(id) on delete cascade, kind text not null check(kind in ('image','video','html')), asset_url text not null, duration_seconds integer not null default 15, active boolean not null default true);
create table prizes (id uuid primary key default gen_random_uuid(), venue_id uuid not null references venues(id) on delete cascade, name text not null, description text, inventory integer, status prize_status not null default 'disabled', rules jsonb not null default '{}', created_at timestamptz not null default now());
create table prize_awards (id uuid primary key default gen_random_uuid(), prize_id uuid not null references prizes(id), player_session_id uuid not null references player_sessions(id), game_session_id uuid references game_sessions(id), claim_code text unique, claimed_at timestamptz, awarded_at timestamptz not null default now());
create table screen_events (id bigint generated always as identity primary key, venue_id uuid not null references venues(id) on delete cascade, screen_key text not null, status text not null, current_game_id text, metadata jsonb not null default '{}', recorded_at timestamptz not null default now());
create index on player_sessions(venue_id,last_seen_at desc); create index on game_sessions(venue_id,created_at desc); create index on campaigns(venue_id,status); create index on screen_events(venue_id,recorded_at desc);
