/// <reference types="vite/client" />
import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useParams } from 'react-router-dom';
import { io } from 'socket.io-client';
import { QRCodeSVG } from 'qrcode.react';
import { gameCatalog } from '@freepour/games';
import './styles.css';

const api = import.meta.env.VITE_API_URL ?? '/api';
function Shell({ children }: { children: React.ReactNode }) { return <><header><Link to="/">FREEPOUR.TV</Link><span>SCAN · PLAY · WIN</span></header><main>{children}</main></>; }
function Home() { return <Shell><section className="hero"><p className="eyebrow">THE BAR IS LIVE</p><h1>Five games.<br/>One shared screen.</h1><p>Open a venue screen or join from the QR code.</p><div className="actions"><Link className="button" to="/venue/demo">Venue screen</Link><Link className="button ghost" to="/play/demo">Player demo</Link><Link className="button ghost" to="/admin">Admin</Link></div></section></Shell>; }
function Player() { const { slug = 'demo' } = useParams(); const [username,setUsername]=useState(''); const [joined,setJoined]=useState(false); async function join(e:React.FormEvent){e.preventDefault(); const response=await fetch(`${api}/player/session`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({venueSlug:slug,username})}); setJoined(response.ok);} return <Shell><section className="card"><p className="eyebrow">JOIN {slug.toUpperCase()}</p>{joined?<><h2>You're in, {username}.</h2><p>Keep this screen open. The next game will begin on the venue screen.</p></>:<form onSubmit={join}><h2>Choose your player name</h2><input autoFocus maxLength={24} value={username} onChange={e=>setUsername(e.target.value)} placeholder="Player name"/><button>Join game</button></form>}</section></Shell>; }
function Venue() { const { slug='demo' }=useParams(); const [index,setIndex]=useState(0); const game=gameCatalog[index%gameCatalog.length]; const joinUrl=`${window.location.origin}/play/${slug}`; useEffect(()=>{const timer=setInterval(()=>setIndex(i=>i+1),12000); const socket=io({auth:{venueId:slug,screenKey:`screen:${slug}`}}); const heartbeat=setInterval(()=>socket.emit('screen:heartbeat',{currentGame:game.id}),15000); return()=>{clearInterval(timer);clearInterval(heartbeat);socket.disconnect()};},[slug,game.id]); return <div className="screen"><div className="screen-top"><strong>FREEPOUR.TV</strong><span>● LIVE</span></div><div className="game"><p className="eyebrow">UP NEXT</p><h1>{game.name}</h1><p>{game.description}</p><div className="qr"><QRCodeSVG value={joinUrl} size={184} level="M" marginSize={2}/></div><strong>{joinUrl.replace(/^https?:\/\//,'')}</strong></div><div className="ticker">SCAN · PICK A NAME · PLAY FREE</div></div>; }
function Admin() { return <Shell><section><p className="eyebrow">VENUE CONTROL</p><h1>Game rotation</h1><div className="grid">{gameCatalog.map((game,i)=><article className="game-card" key={game.id}><span>{String(i+1).padStart(2,'0')}</span><h2>{game.name}</h2><p>{game.description}</p><label><input type="checkbox" defaultChecked/> Enabled</label></article>)}</div><aside><h2>Prizes</h2><p>Present in the platform and disabled by default. Enable only after venue rules and fulfillment are configured.</p><button disabled>Disabled</button></aside></section></Shell>; }
function App(){return <BrowserRouter><Routes><Route path="/" element={<Home/>}/><Route path="/play/:slug" element={<Player/>}/><Route path="/venue/:slug" element={<Venue/>}/><Route path="/admin" element={<Admin/>}/></Routes></BrowserRouter>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
