/// <reference types="vite/client" />
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useParams } from 'react-router-dom';
import { io } from 'socket.io-client';
import { QRCodeSVG } from 'qrcode.react';
import { gameCatalog } from '@freepour/games';
import { createRound, GameResult, PlayerGameControl, RoundState, scoreInput, VenueGameStage } from './games';
import './styles.css';

const api = import.meta.env.VITE_API_URL ?? '/api';
type VenueGame = { gameId: string; enabled: boolean; position: number; config?: Record<string, unknown> };
type VenueRecord = { id: string; name: string; slug: string; timezone: string; active: boolean; prizes_enabled: boolean; player_count: number; games: VenueGame[] };

function Shell({ children }: { children: React.ReactNode }) { return <><header><Link to="/">FREEPOUR.TV</Link><span>SCAN · PLAY · WIN</span></header><main>{children}</main></>; }

function Home() { return <Shell><section className="hero"><p className="eyebrow">THE BAR IS LIVE</p><h1>Five games.<br />One shared screen.</h1><p>Join instantly from your phone—no app and no account required.</p><div className="actions"><Link className="button" to="/venue/demo">Venue screen</Link><Link className="button ghost" to="/play/demo">Player demo</Link><Link className="button ghost" to="/admin">Venue setup</Link></div></section></Shell>; }

function Player() {
  const { slug = 'demo' } = useParams(); const [venueName, setVenueName] = useState(slug.replaceAll('-', ' ')); const [username, setUsername] = useState(''); const [playerId, setPlayerId] = useState(''); const [round, setRound] = useState<RoundState | null>(null); const [error, setError] = useState(''); const socketRef = useRef<ReturnType<typeof io> | null>(null);
  useEffect(() => { fetch(`${api}/venues/${slug}/config`).then(r => r.ok ? r.json() : null).then(v => v?.name && setVenueName(v.name)); }, [slug]);
  useEffect(() => { if (!playerId) return; const socket = io({ auth: { venueId: slug, playerId, username } }); socketRef.current = socket; socket.on('game:state', (state: RoundState) => setRound(state)); return () => { socket.disconnect(); socketRef.current = null; }; }, [playerId, slug, username]);
  async function join(e: React.FormEvent) { e.preventDefault(); setError(''); const response = await fetch(`${api}/player/session`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ venueSlug: slug, username }) }); if (!response.ok) return setError(response.status === 404 ? 'This venue is not available yet.' : 'Choose a name with at least two letters.'); const session = await response.json(); setPlayerId(session.id); }
  function submit(action: string, value?: number | string) { socketRef.current?.emit('game:input', { roundId: round?.roundId, gameId: round?.gameId, playerId, username, action, value }); }
  return <div className="player-page"><div className="player-brand">FREEPOUR.TV <span>{venueName}</span></div>{playerId ? <section className="play-surface">{round ? <PlayerGameControl state={round} onSubmit={submit} /> : <div className="joined"><span>✓</span><h2>You're in, {username}.</h2><p>Watch the TV. The next round will appear here automatically.</p></div>}</section> : <section className="join-card"><p className="eyebrow">JOINING</p><h1>{venueName}</h1><form onSubmit={join}><label htmlFor="player-name">Your player name</label><input id="player-name" autoComplete="nickname" autoFocus maxLength={24} value={username} onChange={e => setUsername(e.target.value)} placeholder="e.g. Lucky 7" /><button disabled={username.trim().length < 2}>Join the game</button>{error && <p className="form-error" role="alert">{error}</p>}<small>No download. No account. Just play.</small></form></section>}</div>;
}

function Venue() {
  const { slug = 'demo' } = useParams(); const [index, setIndex] = useState(0); const [venueName, setVenueName] = useState('FreePour'); const [rotation, setRotation] = useState(gameCatalog); const [round, setRound] = useState<RoundState>(() => createRound('quick-draw', 0)); const [results, setResults] = useState<GameResult[]>([]); const game = rotation[index % rotation.length] ?? gameCatalog[0]; const joinUrl = `${window.location.origin}/play/${slug}`; const socketRef = useRef<ReturnType<typeof io> | null>(null); const roundRef = useRef(round);
  useEffect(() => { fetch(`${api}/venues/${slug}/config`).then(r => r.ok ? r.json() : null).then(config => { if (!config) return; setVenueName(config.name); const enabled = [...config.games].filter((item: VenueGame) => item.enabled).sort((a: VenueGame, b: VenueGame) => a.position - b.position).map((item: VenueGame) => gameCatalog.find(g => g.id === item.gameId)).filter(Boolean) as typeof gameCatalog; if (enabled.length) setRotation(enabled); }); }, [slug]);
  useEffect(() => { const socket = io({ auth: { venueId: slug, screenKey: `screen:${slug}` } }); socketRef.current = socket; socket.on('game:input', (input: Omit<GameResult, 'score'>) => { const active = roundRef.current; if (input.roundId !== active.roundId) return; const result = { ...input, score: scoreInput(active, { ...input, receivedAt: input.receivedAt ?? Date.now() }) } as GameResult; setResults(current => current.some(item => item.playerId === result.playerId) ? current : [...current, result]); }); const heartbeat = setInterval(() => socket.emit('screen:heartbeat', { currentGame: roundRef.current.gameId }), 15000); return () => { clearInterval(heartbeat); socket.disconnect(); socketRef.current = null; }; }, [slug]);
  useEffect(() => { const nextRound = createRound(game.id, index); setRound(nextRound); roundRef.current = nextRound; setResults([]); socketRef.current?.emit('game:state', nextRound); const timer = setTimeout(() => setIndex(i => i + 1), game.defaultDurationSeconds * 1000); return () => clearTimeout(timer); }, [game.id, game.defaultDurationSeconds, index]);
  return <div className="screen live-screen"><div className="screen-top"><strong>FREEPOUR.TV</strong><span>{venueName} · LIVE</span></div><VenueGameStage state={round} results={results} /><div className="screen-join"><div className="qr"><QRCodeSVG value={joinUrl} size={184} level="M" marginSize={2} /></div><strong>{joinUrl.replace(/^https?:\/\//, '')}</strong></div><div className="ticker">SCAN · JOIN · PLAY LIVE</div></div>;
}

function Admin() {
  const [configured, setConfigured] = useState<boolean | null>(null); const [token, setToken] = useState(() => localStorage.getItem('freepour_token') ?? ''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [venues, setVenues] = useState<VenueRecord[]>([]); const [selectedId, setSelectedId] = useState(''); const [showCreate, setShowCreate] = useState(false); const [name, setName] = useState(''); const [slug, setSlug] = useState(''); const [timezone, setTimezone] = useState('America/Los_Angeles'); const [message, setMessage] = useState(''); const selected = venues.find(v => v.id === selectedId); const authHeaders = useMemo(() => ({ 'content-type': 'application/json', authorization: `Bearer ${token}` }), [token]);
  useEffect(() => { fetch(`${api}/setup/status`).then(r => r.json()).then(r => setConfigured(r.configured)).catch(() => setConfigured(true)); }, []);
  useEffect(() => { if (token) void loadVenues(); }, [token]);
  async function loadVenues() { const response = await fetch(`${api}/admin/venues`, { headers: { authorization: `Bearer ${token}` } }); if (response.status === 401) { localStorage.removeItem('freepour_token'); setToken(''); return; } if (response.ok) setVenues(await response.json()); }
  async function authenticate(e: React.FormEvent) { e.preventDefault(); setMessage(''); const route = configured ? 'auth/login' : 'setup/bootstrap'; const response = await fetch(`${api}/${route}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password }) }); if (!response.ok) return setMessage(configured ? 'Email or password did not match.' : 'Use a valid email and a password of at least 12 characters.'); const data = await response.json(); localStorage.setItem('freepour_token', data.token); setToken(data.token); setConfigured(true); }
  async function createVenue(e: React.FormEvent) { e.preventDefault(); setMessage(''); const response = await fetch(`${api}/admin/venues`, { method: 'POST', headers: authHeaders, body: JSON.stringify({ name, slug, timezone }) }); if (!response.ok) return setMessage(response.status === 409 ? 'That venue URL is already in use.' : 'Check the venue details and try again.'); const created = await response.json(); setName(''); setSlug(''); setShowCreate(false); await loadVenues(); setSelectedId(created.id); setMessage(`${created.name} is ready.`); }
  function updateName(value: string) { setName(value); setSlug(value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')); }
  function toggleGame(gameId: string) { if (!selected) return; setVenues(current => current.map(v => v.id !== selected.id ? v : { ...v, games: v.games.map(g => g.gameId === gameId ? { ...g, enabled: !g.enabled } : g) })); }
  function moveGame(gameId: string, direction: -1 | 1) { if (!selected) return; const ordered = [...selected.games].sort((a, b) => a.position - b.position); const at = ordered.findIndex(g => g.gameId === gameId); const next = at + direction; if (next < 0 || next >= ordered.length) return; [ordered[at], ordered[next]] = [ordered[next], ordered[at]]; ordered.forEach((g, position) => g.position = position); setVenues(current => current.map(v => v.id === selected.id ? { ...v, games: ordered } : v)); }
  async function saveGames() { if (!selected) return; const response = await fetch(`${api}/venues/${selected.id}/games`, { method: 'PUT', headers: authHeaders, body: JSON.stringify(selected.games) }); setMessage(response.ok ? 'Game rotation saved.' : 'Could not save the rotation.'); }
  if (configured === null) return <Shell><div className="admin-loading">Loading venue setup…</div></Shell>;
  if (!token) return <Shell><section className="auth-panel"><p className="eyebrow">{configured ? 'VENUE ADMIN' : 'FIRST-TIME SETUP'}</p><h1>{configured ? 'Welcome back.' : 'Create your admin.'}</h1><p>{configured ? 'Sign in to manage venues and screens.' : 'This one-time step creates the owner account for FreePour.'}</p><form onSubmit={authenticate}><label>Email<input type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" autoComplete={configured ? 'current-password' : 'new-password'} value={password} onChange={e => setPassword(e.target.value)} minLength={configured ? 8 : 12} required /></label><button>{configured ? 'Sign in' : 'Create admin account'}</button>{message && <p className="form-error">{message}</p>}</form></section></Shell>;
  return <Shell><section className="admin-shell"><div className="admin-title"><div><p className="eyebrow">FREEPOUR CONTROL</p><h1>Your venues</h1><p>Add locations, open their TV screens, and choose each game rotation.</p></div><button onClick={() => setShowCreate(true)}>+ Add venue</button></div>{message && <div className="notice">{message}</div>}{showCreate && <form className="venue-form" onSubmit={createVenue}><div><p className="eyebrow">NEW VENUE</p><h2>Set up a location</h2></div><label>Venue name<input value={name} onChange={e => updateName(e.target.value)} placeholder="Bar ONO" required /></label><label>Venue URL<input value={slug} onChange={e => setSlug(e.target.value.toLowerCase())} placeholder="bar-ono" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /><small>freepour.tv/play/{slug || 'venue-name'}</small></label><label>Timezone<select value={timezone} onChange={e => setTimezone(e.target.value)}><option>America/Los_Angeles</option><option>America/Denver</option><option>America/Chicago</option><option>America/New_York</option></select></label><div className="form-actions"><button type="button" className="button ghost" onClick={() => setShowCreate(false)}>Cancel</button><button>Create venue</button></div></form>}
  <div className="venue-layout"><div className="venue-list">{venues.length === 0 && <div className="empty-state"><h2>No venues yet</h2><p>Add Bar ONO or Tribute to create its player link and TV screen.</p></div>}{venues.map(venue => <button className={`venue-row ${selectedId === venue.id ? 'selected' : ''}`} key={venue.id} onClick={() => setSelectedId(venue.id)}><span className="venue-avatar">{venue.name.slice(0, 2).toUpperCase()}</span><span><strong>{venue.name}</strong><small>/{venue.slug} · {venue.player_count} players</small></span><i>{venue.active ? 'LIVE' : 'OFF'}</i></button>)}</div>
  <div className="venue-detail">{!selected ? <div className="empty-state"><h2>Select a venue</h2><p>Its links and game rotation will appear here.</p></div> : <><div className="detail-head"><div><p className="eyebrow">VENUE SETUP</p><h2>{selected.name}</h2><p>{selected.timezone}</p></div><span className="status-pill">{selected.active ? 'Active' : 'Paused'}</span></div><div className="link-grid"><a href={`/venue/${selected.slug}`} target="_blank"><span>TV screen</span><strong>Open display ↗</strong></a><a href={`/play/${selected.slug}`} target="_blank"><span>Player link</span><strong>Test join ↗</strong></a></div><div className="rotation-head"><div><h3>Game rotation</h3><p>Enable games and set their TV order.</p></div><button onClick={saveGames}>Save rotation</button></div><div className="rotation-list">{[...selected.games].sort((a, b) => a.position - b.position).map((item, i) => { const game = gameCatalog.find(g => g.id === item.gameId); return <div className={`rotation-row ${item.enabled ? '' : 'disabled'}`} key={item.gameId}><span className="order">{i + 1}</span><div><strong>{game?.name ?? item.gameId}</strong><small>{game?.description}</small></div><div className="move-buttons"><button aria-label="Move up" onClick={() => moveGame(item.gameId, -1)} disabled={i === 0}>↑</button><button aria-label="Move down" onClick={() => moveGame(item.gameId, 1)} disabled={i === selected.games.length - 1}>↓</button></div><label className="switch"><input type="checkbox" checked={item.enabled} onChange={() => toggleGame(item.gameId)} /><span /></label></div>; })}</div><div className="prize-note"><div><p className="eyebrow">PRIZES</p><strong>Disabled by default</strong><p>Prize support is present, but stays off until venue rules and fulfillment are configured.</p></div><span>OFF</span></div></>}</div></div></section></Shell>;
}
function App() { return <BrowserRouter><Routes><Route path="/" element={<Home />} /><Route path="/play/:slug" element={<Player />} /><Route path="/venue/:slug" element={<Venue />} /><Route path="/admin" element={<Admin />} /></Routes></BrowserRouter>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
